// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukHt5dcQc9OR2BFQpCnV-Rzb5Ef3uF84',
    appId: '1:406267808015:web:2840c1b359a0a1994b567a',
    messagingSenderId: '406267808015',
    projectId: 'instagram1-bc923',
    authDomain: 'instagram1-bc923.firebaseapp.com',
    storageBucket: 'instagram1-bc923.appspot.com',
    measurementId: 'G-DGSNQ85BP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWHz-fLNxTv14f7030wHRXI9V3yomftM',
    appId: '1:406267808015:android:1f433bfc8f5951d74b567a',
    messagingSenderId: '406267808015',
    projectId: 'instagram1-bc923',
    storageBucket: 'instagram1-bc923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ34Vna67bKptdikpnil-f7qetbEW0cI4',
    appId: '1:406267808015:ios:ca7421677d15ea984b567a',
    messagingSenderId: '406267808015',
    projectId: 'instagram1-bc923',
    storageBucket: 'instagram1-bc923.appspot.com',
    iosClientId: '406267808015-dh62jc4g1df0vbdnrfeg3erjfbbaf56e.apps.googleusercontent.com',
    iosBundleId: 'com.example.instlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ34Vna67bKptdikpnil-f7qetbEW0cI4',
    appId: '1:406267808015:ios:ca7421677d15ea984b567a',
    messagingSenderId: '406267808015',
    projectId: 'instagram1-bc923',
    storageBucket: 'instagram1-bc923.appspot.com',
    iosClientId: '406267808015-dh62jc4g1df0vbdnrfeg3erjfbbaf56e.apps.googleusercontent.com',
    iosBundleId: 'com.example.instlogin',
  );
}
